resource "random_password" "clickhouse_password" {
  length      = 16
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
  special     = false
}

resource "random_password" "postgres_ro_password" {
  length  = 16
  special = false
}

resource "random_password" "redis_password" {
  length  = 12
  special = false
}

# Token consumed by the server's /livez and /readyz probes. Generated by
# default; can be overridden via var.status_check_token. Alphanumeric only to
# stay YAML- and HTTP-header-safe.
resource "random_password" "status_check_token" {
  length  = 48
  special = false
}
