# Output the infrastructure configuration to console
output "infra_config" {
  description = "Infrastructure configuration for Datafold deployment"
  value = templatefile(
    "${path.module}/../templates/infra_settings.tpl",
    {
      aws_target_group_arn           = "",
      gcp_backup_account             = module.gcp.clickhouse_backup_sa,
      clickhouse_data_size           = module.gcp.clickhouse_data_size,
      clickhouse_data_volume_id      = module.gcp.clickhouse_data_volume_id,
      clickhouse_gcs_bucket          = module.gcp.clickhouse_gcs_bucket,
      clickhouse_logs_size           = module.gcp.clickhouse_logs_size,
      clickhouse_log_volume_id       = module.gcp.clickhouse_logs_volume_id,
      clickhouse_s3_bucket           = "",
      clickhouse_s3_region           = "",
      clickhouse_s3_backup_role      = "",
      clickhouse_azblob_client_id    = "",
      clickhouse_azblob_container    = "",
      clickhouse_azblob_account_name = "",
      cloud_provider                 = module.gcp.cloud_provider,
      cluster_name                   = module.gcp.cluster_name,
      gcp_neg_name                   = module.gcp.neg_name,
      load_balancer_ips              = jsondecode(module.gcp.lb_external_ip),
      load_balancer_controller_arn   = "",
      cluster_scaler_role_arn        = "",
      postgres_database              = local.database_name,
      postgres_password              = module.gcp.postgres_password,
      postgres_port                  = module.gcp.postgres_port,
      postgres_server                = module.gcp.postgres_host,
      postgres_user                  = module.gcp.postgres_username,
      redis_data_size                = module.gcp.redis_data_size,
      redis_data_volume_id           = module.gcp.redis_data_volume_id,
      server_name                    = module.gcp.domain_name,
      vpc_cidr                       = module.gcp.vpc_cidr,

      # service accounts vars
      dfshell_role_arn                        = module.gcp.dfshell_role_arn,
      dfshell_service_account_name            = module.gcp.dfshell_service_account_name,
      worker_portal_role_arn                  = module.gcp.worker_portal_role_arn,
      worker_portal_service_account_name      = module.gcp.worker_portal_service_account_name,
      operator_role_arn                       = module.gcp.operator_role_arn,
      operator_service_account_name           = module.gcp.operator_service_account_name,
      server_role_arn                         = module.gcp.server_role_arn,
      server_service_account_name             = module.gcp.server_service_account_name,
      scheduler_role_arn                      = module.gcp.scheduler_role_arn,
      scheduler_service_account_name          = module.gcp.scheduler_service_account_name,
      worker_role_arn                         = module.gcp.worker_role_arn,
      worker_service_account_name             = module.gcp.worker_service_account_name,
      worker_catalog_role_arn                 = module.gcp.worker_catalog_role_arn,
      worker_catalog_service_account_name     = module.gcp.worker_catalog_service_account_name,
      worker_interactive_role_arn             = module.gcp.worker_interactive_role_arn,
      worker_interactive_service_account_name = module.gcp.worker_interactive_service_account_name,
      worker_singletons_role_arn              = module.gcp.worker_singletons_role_arn,
      worker_singletons_service_account_name  = module.gcp.worker_singletons_service_account_name,
      worker_lineage_role_arn                 = module.gcp.worker_lineage_role_arn,
      worker_lineage_service_account_name     = module.gcp.worker_lineage_service_account_name,
      worker_monitor_role_arn                 = module.gcp.worker_monitor_role_arn,
      worker_monitor_service_account_name     = module.gcp.worker_monitor_service_account_name,
      storage_worker_role_arn                 = module.gcp.storage_worker_role_arn,
      storage_worker_service_account_name     = module.gcp.storage_worker_service_account_name,
    }
  )
  sensitive = false
}
